### PR TITLE
Misc changes around dependency updates, kotlin-java protobuf duplicate issues on Android. and code generation.

### PR DESCRIPTION
**Pull request by Anmol92verma**
iOS works only with Xcode 13.0 and not 14.0.1 as of now, seen issues with gRPC not compiling.

### CODE REVIEW

**Comment by TimOrtel** [comment]
Thank you for this pull request. Please only open pull requests to the develop branch, not the master branch.

**Review by TimOrtel — COMMENTED** [review]
It is not quite clear why you introduced the changes you have made, please elaborate on these. For example, why did you introduce the Android enum field to the gradle configuration?

**Comment by Anmol92verma** [comment]
Question: Can I use something like this to fix it ?

    targetSourcesMap.put(OutputTarget.JVM, listOf(kotlin.sourceSets.getByName("jvmMain"),
kotlin.sourceSets.getByName("androidMain")))

**Comment by TimOrtel** [comment]
Yes, this is the way android is configured in the test module. Therefore, I do not really see why we need this android enum field.

**Comment by Anmol92verma** [comment]
@TimOrtel the example project is outdated and the readme doesn't explain that, I will try if that works.

**Comment by TimOrtel** [comment]
A lot of your changes are line indentation changes. Can you please revert them, as this messes with git blame etc. Four spaces for indentation should be the correct setting.

**Pull request closed without merging**
